-- AlterEnum
ALTER TYPE "HomeSectionKind" ADD VALUE 'TRUST_STRIP';
ALTER TYPE "HomeSectionKind" ADD VALUE 'CATEGORY_ICONS';
ALTER TYPE "HomeSectionKind" ADD VALUE 'RAIL_BESTSELLERS';
ALTER TYPE "HomeSectionKind" ADD VALUE 'RAIL_POPULAR';
ALTER TYPE "HomeSectionKind" ADD VALUE 'RAIL_NEWEST';
ALTER TYPE "HomeSectionKind" ADD VALUE 'STORY_STRIP';
ALTER TYPE "HomeSectionKind" ADD VALUE 'PROMO_BANNER';
ALTER TYPE "HomeSectionKind" ADD VALUE 'PRODUCT_CATALOG';
