-- Product SEO extensions
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoCanonicalUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoOgImageUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoNoIndex" BOOLEAN NOT NULL DEFAULT false;

-- Category SEO
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "metaTitle" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "metaDescription" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "seoCanonicalUrl" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "seoOgImageUrl" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "seoNoIndex" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CMS Page SEO
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "metaTitle" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "metaDescription" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seoCanonicalUrl" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seoOgImageUrl" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seoNoIndex" BOOLEAN NOT NULL DEFAULT false;

-- SiteSettings: home / shop / contact page SEO
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "homeMetaTitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "homeMetaDesc" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "homeSeoKeywords" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "homeCanonicalUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "homeOgImageUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "homeNoIndex" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "shopMetaTitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "shopMetaDesc" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "shopSeoKeywords" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "shopCanonicalUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "shopOgImageUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "shopNoIndex" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "contactMetaTitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "contactMetaDesc" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "contactSeoKeywords" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "contactCanonicalUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "contactOgImageUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "contactNoIndex" BOOLEAN NOT NULL DEFAULT false;
